<?php
/**********************************************/
/* Freddy - Baseado na Engine do Php-Nuke 7.5 */
/* ------------------------------------------ */
/*                                            */
/* Freddy é um Software Livre liberado sob    */
/* Licença GNU/GPL.                           */
/*                                            */
/* CoDeD By HellNeT InterneT Services         */
/* Desenvolvedor: Giuliano Cardoso            */
/**********************************************/
/* Baseado no Php-Nuke 7.5                    */
/* http://www.phpnuke.org                     */
/**********************************************/
//Sobre a  Licença GNU/GPL - http://www.gnu.org
/************************************************************************************/
/*  Freedy é um software livre; você pode redistribui-lo e/ou                       */
/*  modifica-lo dentro dos termos da Licença Pública Geral GNU como                 */
/*  publicada pela Fundação do Software Livre (FSF); na versão 2 da                 */
/*  Licença.                                                                        */
/*                                                                                  */
/*  O Freddy é distribuido na esperança que possa ser  util,                        */
/*  mas SEM NENHUMA GARANTIA; sem uma garantia implicita de ADEQUAÇÂO a qualquer    */
/*  MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a                                      */
/*  Licença Pública Geral GNU para maiores detalhes.                                */
/*                                                                                  */
/*  Você deve ter recebido uma cópia da Licença Pública Geral GNU                   */
/*  junto com este programa, se não, escreva para a Fundação do Software            */
/*  Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA       */
/************************************************************************************/

define("_SEND","Enviar");
define("_URL","URL");
define("_EMAIL","e-mail");
define("_FUNCTIONS","Funções");
define("_YES","sim");
define("_NO","Não");
define("_REQUIRED","(requerido)");
define("_SAVECHANGES","Salvar alterações");
define("_OK","Ok!");
define("_SAVE","Salvar");
define("_ID","ID");
define("_SUBJECT","Assunto");
define("_WHOSONLINE","quem está on-line");
define("_ARTICLES","Notícias");
define("_ALL","Todos(as)");
define("_PREVIEW","Pré-visualizar");
define("_EXTRAINFO","Informações adicionais");
define("_YOUARELOGGEDOUT","Você efetuou o logoff de sua Conta");
define("_HOMECONFIG","configuração da Home");
define("_DESCRIPTION","Descrição");
define("_HOMEPAGE","HomePage");
define("_NAME","Nome");
define("_FROM","De");
define("_TO","Para");
define("_SUBMIT","enviar");
define("_SHOW","mostrar");
define("_DAYS","dias");
define("_STAFF","Equipe");
define("_ADMINID","ID do Administrador");
define("_ADMINLOGIN","Login do Administrador do Sistema");
define("_EDITADMINS","Editar Administradores");
define("_PREFERENCES","Preferências");
define("_ADMINMENU","Menu de Administração");
define("_BANNERSADMIN","Administração de banners");
define("_ADMINLOGOUT","Logout/Sair");
define("_LAST","Último(a)");
define("_GO","Vá!");
define("_CURRENTPOLL","Enquete atual");
define("_STORYID","ID da notícia");
define("_ACTIVEBANNERS","Banners atualmente ativos");
define("_ACTIVEBANNERS2","Bannes ativos");
define("_IMPRESSIONS","Impressões");
define("_IMPLEFT","Impressões restantes");
define("_CLICKS","Cliques");
define("_CLICKSPERCENT","% cliques");
define("_CLIENTNAME","Nome do Cliente");
define("_ADVERTISINGCLIENTS","Clientes anunciantes");
define("_CONTACTNAME","Nome do contato");
define("_CONTACTEMAIL","e-mail do contato");
define("_ADDNEWBANNER","Adicione um novo banner");
define("_PURCHASEDIMPRESSIONS","Impressões compradas");
define("_IMAGEURL","URL para a imagem");
define("_CLICKURL","URL do clique");
define("_ADDBANNER","Adicionar banner");
define("_ADDCLIENT","Adicionar um novo cliente");
define("_CLIENTLOGIN","Login do Cliente");
define("_CLIENTPASSWD","Senha do Cliente");
define("_ADDCLIENT2","Adicionar Cliente");
define("_DELETEBANNER","apagar banner");
define("_SURETODELBANNER","você tem certeza de que quer apagar este banner?");
define("_EDITBANNER","Editar banner");
define("_ADDIMPRESSIONS","Adicionar mais impressões");
define("_PURCHASED","Compradas");
define("_MADE","Feito(a)");
define("_DELETECLIENT","Apagar Cliente anunciante");
define("_SURETODELCLIENT","Você está prestes a apagar este cliente e todos os seus banners!!!");
define("_CLIENTWITHOUTBANNERS","Este cliente não possui nenhum banner ativo.");
define("_DELCLIENTHASBANNERS","Este cliente possui os seguintes banners ativos");
define("_EDITCLIENT","Editar Cliente anunciante");
define("_REMOVECOMMENTS","Apagar comentários");
define("_SURETODELCOMMENTS","Você tem certeza de que quer apagar o comentário selecionado e todas as respostas???");
define("_BLOCKSADMIN","Administração de Blocos");
define("_BLOCKS","Blocos");
define("_TITLE","Título");
define("_POSITION","Posição");
define("_WEIGHT","Peso");
define("_STATUS","Status");
define("_LEFTBLOCK","Esquerda");
define("_LEFT","Esquerda");
define("_RIGHTBLOCK","Direita");
define("_RIGHT","Direita");
define("_ACTIVE","Ativo");
define("_DEACTIVATE","Desativar");
define("_INACTIVE","Inativo");
define("_ACTIVATE","Ativar");
define("_TYPE","Tipo");
define("_ADDNEWBLOCK","Adicionar novo Bloco");
define("_RSSFILE","URL para arquivo RSS/RDF");
define("_ONLYHEADLINES","(Apenas para as manchetes (headlines)");
define("_CONTENT","Conteúdo");
define("_ACTIVATE2","Ativar?");
define("_REFRESHTIME","Tempo para atualizar");
define("_HOUR","Hora");
define("_CREATEBLOCK","Criar Bloco");
define("_EDITBLOCK","Editar Bloco");
define("_BLOCK","Bloco");
define("_SAVEBLOCK","Salvar Bloco");
define("_BLOCKACTIVATION","Ativação do Bloco");
define("_BLOCKPREVIEW","Esta é a previsão do Bloco.");
define("_WANT2ACTIVATE","Você deseja ativar este Bloco?");
define("_ARESUREDELBLOCK","Você tem certeza de que quer remover este Bloco?");
define("_RSSFAIL","Há um problema com a URL do arquivo RSS/RDF!");
define("_RSSTRYAGAIN","Por favor, verifique a URL e tente novamente.");
define("_RSSCONTENT","(Conteúdo RSS/RDF)");
define("_IFRSSWARNING","Se você inserir uma URL o conteúdo que você digitar abaixo não será mostrado!");
define("_BLOCKUP","Subir Bloco");
define("_BLOCKDOWN","Baixar Bloco");
define("_SETUPHEADLINES","(Selecione Customizado e digite a URL ou selecione um site da lista abaixo para ter acesso às manchetes)");
define("_HEADLINESADMIN","Administração de Manchetes");
define("_ADDHEADLINE","Adicionar Manchetes");
define("_EDITHEADLINE","Editar Manchetes");
define("_SURE2DELHEADLINE","<b>AVISO</b>: Você tem certeza de que quer apagar estas manchetes???");
define("_CUSTOM","Customizado");
define("_AUTHORSADMIN","Gerenciamento de Administradores");
define("_MODIFYINFO","Modificar informações");
define("_DELAUTHOR","Apagar Administrador");
define("_ADDAUTHOR","Adicionar Administrador");
define("_PERMISSIONS","Permissões");
define("_USERS","Usuários");
define("_SUPERUSER","Super Usuário");
define("_SUPERWARNING","<b>AVISO</b>: Se você selecionar <b>Super Usuário</b> o usuário terá ACESSO TOTAL!!!");
define("_ADDAUTHOR2","Adicionar Administrador");
define("_RETYPEPASSWD","Digite a senha novamente");
define("_FORCHANGES","(Apenas para alterações)");
define("_COMPLETEFIELDS","Você deve preencher todos os campos requeridos");
define("_CREATIONERROR","Erro na criação de Administrador");
define("_AUTHORDELSURE","Você tem certeza de que quer apagar");
define("_AUTHORDEL","Apagar Administrador");
define("_REQUIREDNOCHANGE","(requerido, NÃO PODE ser alterado depois)");
define("_PUBLISHEDSTORIES","Este administrador publicou notícias");
define("_SELECTNEWADMIN","Por favor, selecione outro Administrador para tomar o lugar deste");
define("_GODNOTDEL","*(A conta GOD account NÃO PODE ser apagada!!!)");
define("_MAINACCOUNT","God Admin*");
define("_ADD","Adicionar");
define("_DAY","Dia");
define("_AUTOMATEDARTICLES","Notícias progrmadas");
define("_NOAUTOARTICLES","Não há notícias programadas");
define("_WARNING","<b>Aviso</a>");
define("_NOFUNCTIONS","---------");
define("_WHOLINKS","Quem está referenciando nosso site?");
define("_DELETEREFERERS","Apagar referenciadores");
define("_SITENAME","Nome do site");
define("_PASSWDNOMATCH","Desculpe, mas as novas senhas nãocoincidem! Volte e tente novamente.");
define("_SITECONFIG","Configuração do site");
define("_GENSITEINFO","Informações gerais do site");
define("_SITEURL","URL do site");
define("_SITELOGO","Logo do site");
define("_SITESLOGAN","Slogan do site");
define("_ADMINEMAIL","e-mail do Administrador");
define("_ITEMSTOP","Número de itens na página de Top");
define("_STORIESHOME","Número de notícias na Home");
define("_OLDSTORIES","Notícias no Bloco Notícias Antigas");
define("_ACTULTRAMODE","Ativar Ultramode?");
define("_DEFAULTTHEME","Tema padrão para seu site");
define("_SELLANGUAGE","Selecione o idioma para seu site");
define("_LOCALEFORMAT","Formato para a hora local");
define("_BANNERSOPT","Opções de banners");
define("_STARTDATE","Data de lançamento do site");
define("_ACTBANNERS","Deseja ativar banners em seu site?");
define("_FOOTERMSG","Mensgens do rodapé");
define("_FOOTERLINE1","Rodapé: linha 1");
define("_FOOTERLINE2","Rodapé: linha 2");
define("_FOOTERLINE3","Rodapé: linha 3");
define("_BACKENDCONF","Configuração de fundo");
define("_BACKENDTITLE","Título de fundo");
define("_BACKENDLANG","Idioma de fundo");
define("_MAIL2ADMIN","Enviar novas notícias para o e-mail do Administrador?");
define("_NOTIFYSUBMISSION","Notificar novos envios por e-mail?");
define("_EMAIL2SENDMSG","e-mail para ser enviada a mensagem");
define("_EMAILSUBJECT","Assunto do e-mail");
define("_EMAILMSG","Mensagem do e-mail");
define("_EMAILFROM","Conta de e-mail (De)");
define("_COMMENTSMOD","Moderação de comentários");
define("_MODTYPE","Tipo de moderação");
define("_MODADMIN","Moderado pelo Administrador");
define("_MODUSERS","Moderado pelos usuários");
define("_NOMOD","Sem moderação");
define("_COMMENTSOPT","Opção de comentários");
define("_COMMENTSLIMIT","Limite para os comentários (bytes)");
define("_ANONYMOUSNAME","Nome padrão para usuários anônimos");
define("_GRAPHICOPT","Opções gráficas");
define("_ADMINGRAPHIC","Gráficos no Menu de Administração?");
define("_MISCOPT","Opções diversas");
define("_PASSWDLEN","Mínimo de caracteres para senha dos usuários");
define("_MAXREF","Quantos referenciadores você deseja ter como máximo?");
define("_COMMENTSPOLLS","Ativar comentários nas Enquetes?");
define("_ALLOWANONPOST","Permitir envios de usuários anônimos?");
define("_ACTIVATEHTTPREF","Ativar Referências HTTP?");
define("_SIZE","Tamanho");
define("_MESSAGES","Mensagens");
define("_MESSAGESADMIN","Administração de Mensagens");
define("_MESSAGETITLE","Título");
define("_MESSAGECONTENT","Conteúdo");
define("_EXPIRATION","Expira em");
define("_VIEWPRIV","Quem pode ver esta Mensagem?");
define("_MVADMIN","Apenas Administradores");
define("_MVUSERS","Apenas usuários cadastrados");
define("_MVANON","Apenas usuários anônimos");
define("_MVALL","TODOS");
define("_CHANGEDATE","Alterar a data de início para hoje?");
define("_IFYOUACTIVE","(Se você ativar esta Mensagem agora, a data de início será hoje!)");
define("_FILENAME","Nome do arquivo");
define("_FILEINCLUDE","(Selecione um Bloco Customizado para ser incluído. Todos os outros campos serão ignorados.)");
define("_BLOCKFILE","(Arquivo de Bloco)");
define("_COMMENTSARTICLES","Ativar comentários nas notícias?");
define("_MULTILINGUALOPT","Opões multi-idioma");
define("_ACTMULTILINGUAL","Ativar funções multi-idioma?");
define("_ACTUSEFLAGS","Mostrar bandeiras ao invés de uma caixa drop-down?");
define("_LANGUAGE","Idioma");
define("_EDITMSG","Editar Messagem");
define("_ADDMSG","Adicionar Messagem");
define("_ALLMESSAGES","Vizualizar Messagens");
define("_VIEW","Visível para");
define("_REMOVEMSG","VoCê tem certeza de que quer remover esta Mensagem?");
define("_MODULES","Módulos");
define("_MODULESADMIN","Administração de Módulos");
define("_MODULESADDONS","Módulos e Adicionais");
define("_MODULESACTIVATION","Veja o status dos Módulos instalados, ative-os e desative-os.<br>Novos Módulos instalados no diretório <i>/modules/</i> irão aparecer aqui automaticamente, porém terão o status <i>Inativo</i>.<br>Se você quiser desinstalar um Módulo, basta apagar o diretório correspondente ao name do Módulo no diretório <i>/modules/</i>, e o Sistema será automaticamente atualizado.");
define("_NEWSLETTER","Newsletter");
define("_MASSMAIL","Um e-mail MASSIVO para TODOS os usuários");
define("_ANEWSLETTER","Uma Newsletter somente para os usuários que optaram recebê-la");
define("_WHATTODO","O que você quer enviar?");
define("_SUBSCRIBEDUSERS","Usuários Inscritos");
define("_NYOUAREABOUTTOSEND","Você está prestes a enviar uma Newsletter para todos os usuários inscritos.");
define("_NUSERWILLRECEIVE","Os usuários irão receber esta Newsletter.");
define("_REVIEWTEXT","Por favor, revise a ortografia do seu texto:");
define("_NAREYOUSURE2SEND","VOcê tem certeza de que quer enviar essa Newsletter agora?");
define("_MYOUAREABOUTTOSEND","Você está prestes a enviar uma e-mail MASSIVO para todos os usuários cadastrados .");
define("_MUSERWILLRECEIVE","Os usuários receberão este e-mail.");
define("_MAREYOUSURE2SEND","Você tem certeza de que quer enviar este e-mail agora?");
define("_POSSIBLESPAM","Tenha ciência de que nem todos os usuários se sentem bem em receber Newsletter como e-mail MASSIVO e pode considerar essa atitude como SPAM!");
define("_MASSEMAIL","e-mail MASSIVO");
define("_MANYUSERSNOTE","<b>Aviso</b>: Muitos usuários receberão este texto! Por favor aguarde até que o script termine a operação. Esta operação pode demorar alguns minutos!");
define("_NLUNSUBSCRIBE","=========================================================\nVocê está recebendo esta Newsletter pois está cadastrado como usuário no $sitename.\nSe você não optou por receber esta mensagem, pedimos desculpas antecipadas. Qualquer dúvida, crítica ou sugestão, favor entrar em contato com o Administrador do site.");
define("_NEWSLETTERSENT","A Newsletter foi enviada!");
define("_MASSEMAILSENT","O e-mail MASSIVO para todos os usuários foi enviado.");
define("_MASSEMAILMSG","=========================================================\nVocê está recebendo esta Newsletter pois está cadastrado como usuário no $sitename. Esperamos que este e-mail não o(a) perturbe e que de alguma maneira possa contribuir para melhorar nossos serviços.");
define("_FIXBLOCKS","Reparar conflito de peso dos Blocos");
define("_SAVEDATABASE","Backup do Banco de Dados");
define("_DBOPTIMIZATION","Otimização do Banco de Dados");
define("_OPTIMIZINGDB","Otimizando Banco de Dados:");
define("_TABLE","Tabela");
define("_SPACESAVED","Espaço salvo");
define("_ALREADYOPTIMIZED","Já otimizado");
define("_OPTIMIZED","OTIMIZADO!!!");
define("_OPTIMIZATIONRESULTS","Resultados da otimização");
define("_TOTALSPACESAVED","Total de espaço liberado:");
define("_YOUHAVERUNSCRIPT","Você já rodou este script :");
define("_KBSAVED","Kb salvos desde a primeira execução!");
define("_TIMES","vezes");
define("_CUSTOMTITLE","Título customizado");
define("_CHANGEMODNAME","Alterar o name do Módulo");
define("_CUSTOMMODNAME","Customizar o name do Módulo:");
define("_MODULEEDIT","Editar Móduloes");
define("_BLOCKFILE2","Arquivo");
define("_BLOCKSYSTEM","Sistema");
define("_DEFHOMEMODULE","Módulo padrão na Homepage");
define("_MODULEINHOME","Módulo carregado na Homepage:");
define("_CHANGE","Alterar");
define("_INHOME","na Home");
define("_MODULEHOMENOTE","<b>-= AVISO =-</b><br>O título do Módulo em negrito significa que ele está na Homepage. <br>Você não pode desativá-lo ou restringí-lo enquanto ele for o padrão!<br>Se você apagar este Módulo (o diretório dele em /modules) você verá um erro na Homepage.<br>Este módulo também possui um link par a Home no bloco Módulos.");
define("_PUTINHOME","Colocar na Home");
define("_SURETOCHANGEMOD","Você tem certeza de que quer alterar sua Homepage de");
define("_CENTERBLOCK","Bloco Central");
define("_ADMINISTRATION","Administração");
define("_NOADMINYET","Ainda não foi criada uma conta de administrador. Proceda e crie uma conta de Super Usuário:");
define("_CREATEUSERDATA","Você deseja criar uma conta de usuário normal com os mesmo dados?");
define("_NORMAL","Normal");
define("_INACTIVEBANNERS","Banners inativos");
define("_CENTERUP","No centro, acima");
define("_CENTERDOWN","No centro, abaixo");
define("_NOTINMENU","[ <big><strong>&middot;</strong></big> ] significa que o name de um Módulo e seu link não estarão visíveis no Bloco de Módulos.");
define("_SHOWINMENU","Visível no Bloco de Módulos?");
define("_BANNERS","Banners");
define("_ALTTEXT","Texto alternativo");
define("_MUSTBEINIMG","deve estar no diretório /images/. Válido apenas para o Módulo AVantGo");
define("_USERSOPTIONS","Opções dos usuários");
define("_BROADCASTMSG","Ativar Mensagem Pública?");
define("_MYHEADLINES","Ativar leitor de Manchetes?");
define("_USERSHOMENUM","Permitir que os usuários alterem o número de notícias na Home?");
define("_CENSOROPTIONS","Opções de censura");
define("_CENSORMODE","modo de censura");
define("_NOFILTERING","Sem filtragem");
define("_EXACTMATCH","Coincidir exatamente");
define("_MATCHBEG","Coincidir com palavras começadas");
define("_MATCHANY","Coincidir com qualquer parte da palavra");
define("_CENSORREPLACE","Substituir palavras por:");
define("_SECURITYCODE","Código de Segurança");
define("_TYPESECCODE","Digite o Código de Segurança");
define("_UGROUPS","Grupo de usuários");
define("_POINTS","Pontos");
define("_USERSCOUNT","Conta do usuário");
define("_ADDNEWGROUP","Adicionar novo Grupo de Usuários");
define("_GTITLE","Nome do Grupo");
define("_POINTSNEEDED","Pontos necessários");
define("_ONLYNUMVAL","Use apenas valores numéricos");
define("_CREATEGROUP","Crie este Grupo");
define("_NOGROUPS","Não há nenhum Grupo de Usuários criado até o momento!");
define("_POINTSSYSTEM","Sistema de pontos");
define("_UPDATE","Atualizar");
define("_EDITGROUP","Editar Grupo de Usuários");
define("_SAVEGROUP","Salvar Grupo");
define("_GROUPSADMIN","Administração do Grupo de Usuários");
define("_GROUPADDERROR","Erro na criação do Grupo!");
define("_GROUPDELETE","apagar Grupo de Usuários");
define("_SUREGRPDEL1","Você tem certeza de que quer apagar/remover o Grupo:");
define("_NONUMVALUE","Este valor para os pontos não é numérico. Volte e corrija-o!");
define("_GROUP","Grupo");
define("_UGROUP","Grupo de Usuários");
define("_VALIDIFREG","Válido apenas se usuários cadastrados forem selecionados acima");
define("_POINTS01","Cada Entrada do blog");
define("_DESC01","Entrada no Blog do usuário. Válido para entradas públicas e privadas");
define("_POINTS02","Cada comentário no blog");
define("_DESC02","Cada comentário postado em um blog público");
define("_POINTS03","Cada recomendação a uma pessoa conhecida");
define("_DESC03","Cada vez que o usuário enviar o link do site para uma pessoa conhecida através do Módulo Recomende-nos");
define("_POINTS04","Cada notícia enviada e publicada");
define("_DESC04","Notícias que os usuários enviarem através do Módulo Enviar Notícia e que forem publicadas pela Administração");
define("_POINTS05","Cada comentário nas notícias");
define("_DESC05","comentários publicados para cada notícia");
define("_POINTS06","Cada notícia enviada para uma pessoa conhecida");
define("_DESC06","Cada notícia que for enviada para uma pessoa conhecida. Pontos válidos para cada envio para uma pessoa conhecida");
define("_POINTS07","Cada voto em uma notícia");
define("_DESC07","Cada vez que o usuário votar em uma notícia");
define("_POINTS08","Cada voto em uma Enquete");
define("_DESC08","Cada voto registrado para uma Enquete, atual ou antigas");
define("_POINTS09","Cada comentário enviado a uma Enquete");
define("_DESC09","comentários publicados para a Enquete atual e antigas");
define("_POINTS10","Cada nova mensagem postada nos Foros");
define("_DESC10","Cada vez que o usuário postar uma nov mensagem nos foros");
define("_POINTS11","Cada resposta dada a mensagens postadas nos Foros");
define("_DESC11","Mensagens dos Foros postadas e respondidas");
define("_POINTS12","Cada comentário para Revisão");
define("_DESC12","Comentários publicados para cada Revisão através do Módulo Revisões");
define("_POINTS13","Cada pageview");
define("_DESC13","Ganhe pontos para cada pageview gerada pelo usuário. Válido para qualquer página do site");
define("_POINTS14","Cada visita a um Link");
define("_DESC14","Cada vez que um usuário visitar um Link no do Módulo WebLinks");
define("_POINTS15","Cada votação em um Link");
define("_DESC15","Cada vez que o usuário votar em um Link no do Módulo WebLinks");
define("_POINTS16","Cada comentário para um Link");
define("_DESC16","comentários postados para qualquer Links no Módulo WebLinks");
define("_POINTS17","Cada Download de arquivo");
define("_DESC17","Cada vez que o usuário baixar um arquivo do Módulo Donwloads");
define("_POINTS18","Cada votação em um arquivo");
define("_DESC18","Cada vez que o usuário votar em um arquivo no Módulo Download");
define("_POINTS19","Cada comentário para um arquivo");
define("_DESC19","comentários postados para qualquer arquivo no Módulo de Downloads");
define("_POINTS20","Cada Mensagem Pública enviada");
define("_DESC20","Cada vez que o usuário enviar uma Mensagem Pública usando o Sistema de Mensagem Pública");
define("_POINTS21","Cada clique em qualquer banner");
define("_DESC21","A melhor maneira de devolver algo a um usuário é dar-lhe pontos para cada clique ele der em banners do seu site!");
define("_AFTEREXPIRATION","Após Expirar");
define("_SUBUSERS","Usuários Subscritos");
define("_SUBVISIBLE","Visível para Subscritos?");
define("_IPBANSYSTEM","Sistema de banir IPs");
define("_BANNEWIP","Banir um novo endereço de IP");
define("_IPBANNED","Banir endereço de IP");
define("_BANDATE","Banido em");
define("_UNBAN","Permitir IP");
define("_IPNUMERIC","Um endereço de IP deve ser numérico");
define("_IPENTERED","Endereço de IP introduzido:");
define("_ERROR","ERRO:");
define("_IPOUTRANGE","Endereço de IP fora de alcance");
define("_IPSTARTZERO","Um endereço de IP não pode iniciar com 0");
define("_IPLOCALHOST","Você não pode banir IP local (localhost)");
define("_SUCCESS","Sucesso!!");
define("_THEIP","O endereço de IP");
define("_HASBEENBANNED","foi banido deste site");
define("_SURETOBANIP","Você está certo de que quer permitir este IP?:");
define("_IPYOURS","Você não pode banir seu próprio IP!");
define("_REASON","Razão");


?>
