// PT lang variables

tinyMCE.addToLang('',{
table_desc : 'Insere uma nova tabela',
table_insert_row_before_desc : 'Inserir linha antes',
table_insert_row_after_desc : 'Inserir linha depois',
table_delete_row_desc : 'Eliminar linha',
table_insert_col_before_desc : 'Inserir coluna antes',
table_insert_col_after_desc : 'Inserir coluna depois',
table_delete_col_desc : 'Remover coluna',
insert_table_title : 'Inserir/Modificar tabela',
insert_table_width : 'Largura',
insert_table_height : 'Altura',
insert_table_cols : 'Colunas',
insert_table_rows : 'Linhas',
insert_table_cellspacing : 'Espaçamento',
insert_table_cellpadding : 'Margem interior',
insert_table_border : 'Borda',
insert_table_align : 'Alinhamento',
insert_table_align_default : 'Por omissão',
insert_table_align_left : 'Esquerda',
insert_table_align_right : 'Direita',
insert_table_align_middle : 'Centrado',
insert_table_class : 'Classe de CSS',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Alinhamento Vertical',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Propriedades da Tabela',
table_bordercolor : 'Cor da borda',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Inserir uma nova tabela'
});
